name: Actualizar repositorios

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a medianoche
  workflow_dispatch:  # Permite ejecución manual

permissions:
  contents: write  # Otorga permisos de escritura al bot de GitHub Actions

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Ejecutar script de actualización
        run: ruby .github/workflows/update_repos.rb  # Asegúrate de que la ruta del script es correcta

      - name: Hacer commit y push de los cambios
        run: |
          git add .
          git commit -m "Actualización automática" || echo "Sin cambios"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa el token con permisos correctos
